project_id = "mubmcqhraztyetyvfvaj"

[functions.create-checkout]
verify_jwt = false

[functions.update-payment-status]
verify_jwt = false

[functions.trigger-scraper]
verify_jwt = false

[functions.normalize]
verify_jwt = false