// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mubmcqhraztyetyvfvaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11Ym1jcWhyYXp0eWV0eXZmdmFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxMDc3MjMsImV4cCI6MjA1MTY4MzcyM30.FHSundftU9Zg-DznN44IOPlfw_NRJZG5gTPGDw14ePk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);